(================================================)
( Generated by Langmuir CNC Blender Agent        )
( Controller: Langmuir Systems FireControl        )
( Target: CrossFire PRO / XR Plasma CNC          )
( Units: Inches (G20)                            )
(================================================)
G90 G94
G20
G54
G0 Z1.0000

( --- Cut Profile 1 --- )
G0 X0.0000 Y3.0000
G38.2 Z-5.0000 F60.0 (IHS Probe Material Contact)
G92 Z0.0 (Set Z Work Coordinate Zero)
G0 Z0.0200 (Switch Springback Compensation)
G92 Z0.0
G0 Z0.1500 (Rapid to Pierce Height)
M3 (Plasma Torch ON)
G4 P0.60 (Pierce Delay 0.6s)
G1 Z0.0600 F60.0 (Descend to Cut Height)
H1 (Torch Height Control ON)
G1 X6.0000 Y3.0000 F150.0
G1 X6.0000 Y0.0000 F150.0
G1 X0.0000 Y0.0000 F150.0
G1 X0.0000 Y3.0000 F150.0
H0 (Torch Height Control OFF)
M5 (Plasma Torch OFF)
G0 Z1.0000 (Rapid to Safe Z Height)

M30 (End of Program)
