"""
Langmuir Systems FireControl G-Code Post-Processor.
Produces certified G-code for CrossFire Plasma tables and MR-1 Gantry Mills.
"""

from .langmuir import get_machine_profile

def format_firecontrol_plasma_gcode(
    paths,  # list of paths, each path is list of (x, y) tuples
    machine_name="crossfire_pro",
    material_name="14_gauge_mild_steel",
    output_comment="Part generated by Agentic Blender",
    lead_in=True,
    lead_in_len=0.150
):
    """
    Formats 2D toolpaths into certified FireControl plasma G-code with
    Initial Height Sensing (IHS) touch probe, THC management, pierce routines,
    and anti-blowout linear lead-ins.
    """
    profile = get_machine_profile(machine_name)
    mat = profile.get("materials", {}).get(material_name, {
        "cut_feed_rate": 150.0,
        "pierce_delay": 0.6,
        "pierce_height": 0.15,
        "cut_height": 0.06,
        "amperage": 45,
    })

    safe_z = profile.get("safe_z", 1.0)
    feedrate = mat.get("cut_feed_rate", 150.0)
    delay = mat.get("pierce_delay", 0.6)
    pierce_z = mat.get("pierce_height", 0.15)
    cut_z = mat.get("cut_height", 0.06)
    ihs = profile.get("ihs_enabled", True)
    springback = profile.get("ihs_springback", 0.02)
    thc = profile.get("thc_enabled", True)

    lines = [
        "(================================================)",
        f"( Controller: Langmuir Systems FireControl        )",
        f"( Machine: {profile['name']}            )",
        f"( Material: {material_name} ({mat.get('amperage', 45)}A)        )",
        f"( Note: {output_comment}       )",
        "(================================================)",
        "G90 G94",
        "G20",
        "G54",
        f"G0 Z{safe_z:.4f}",
        ""
    ]

    for idx, path in enumerate(paths, start=1):
        if not path:
            continue
        start_x, start_y = path[0]
        
        # Calculate lead-in offset if requested
        pierce_x, pierce_y = start_x, start_y
        if lead_in and len(path) > 1:
            # Offset pierce position backwards from first cut segment
            dx = path[1][0] - path[0][0]
            dy = path[1][1] - path[0][1]
            dist = (dx**2 + dy**2)**0.5
            if dist > 0.001:
                # Perpendicular or linear lead-in offset
                pierce_x = start_x - (dy / dist) * lead_in_len
                pierce_y = start_y + (dx / dist) * lead_in_len

        lines.append(f"( --- Profile Cut {idx} --- )")
        lines.append(f"G0 X{pierce_x:.4f} Y{pierce_y:.4f}")

        if ihs:
            lines.append("G38.2 Z-5.0000 F60.0 (IHS Probe Contact)")
            lines.append("G92 Z0.0 (Work Z Zero)")
            lines.append(f"G0 Z{springback:.4f} (Springback Offset)")
            lines.append("G92 Z0.0")

        lines.append(f"G0 Z{pierce_z:.4f} (Rapid to Pierce Height)")
        lines.append("M3 (Torch Fire ON)")
        lines.append(f"G4 P{delay:.2f} (Pierce Dwell {delay}s)")
        lines.append(f"G1 Z{cut_z:.4f} F60.0 (Plunge to Cut Height)")

        if thc:
            lines.append("H1 (Torch Height Control ON)")

        # Cut from lead-in pierce point to start of profile
        if lead_in and (pierce_x != start_x or pierce_y != start_y):
            lines.append(f"G1 X{start_x:.4f} Y{start_y:.4f} F{feedrate:.1f} (Lead-in Cut)")

        for pt in path[1:]:
            lines.append(f"G1 X{pt[0]:.4f} Y{pt[1]:.4f} F{feedrate:.1f}")

        if thc:
            lines.append("H0 (Torch Height Control OFF)")

        lines.append("M5 (Torch Extinguish OFF)")
        lines.append(f"G0 Z{safe_z:.4f} (Retract to Safe Z)")
        lines.append("")

    lines.append("M30 (End of Program)")
    lines.append("")
    return "\n".join(lines)

def format_firecontrol_mr1_mill_gcode(
    toolpaths,  # list of dicts: {"z": float, "feed": float, "points": [(x,y), ...]}
    spindle_rpm=6000,
    safe_z=0.5,
    flood_coolant=True
):
    """
    Formats 2.5D milling toolpaths for Langmuir MR-1 CNC Mill.
    """
    lines = [
        "(================================================)",
        "( Machine: Langmuir MR-1 CNC Gantry Mill          )",
        "( Controller: FireControl Milling                 )",
        "( Units: Inches (G20)                            )",
        "(================================================)",
        "G90 G94",
        "G20",
        "G54",
        f"G0 Z{safe_z:.4f}",
        f"M3 S{spindle_rpm} (Spindle Forward)",
    ]

    if flood_coolant:
        lines.append("M8 (Flood Coolant ON)")

    lines.append("G4 P2.0 (Spindle Spin-up Dwell)")
    lines.append("")

    for idx, pass_data in enumerate(toolpaths, start=1):
        z_depth = pass_data.get("z", -0.05)
        feed = pass_data.get("feed", 40.0)
        pts = pass_data.get("points", [])
        if not pts:
            continue

        lines.append(f"( --- Mill Pass {idx} at Z={z_depth:.4f} --- )")
        lines.append(f"G0 X{pts[0][0]:.4f} Y{pts[0][1]:.4f}")
        lines.append(f"G1 Z{z_depth:.4f} F15.0 (Plunge)")

        for pt in pts[1:]:
            lines.append(f"G1 X{pt[0]:.4f} Y{pt[1]:.4f} F{feed:.1f}")

        lines.append(f"G0 Z{safe_z:.4f} (Retract)")
        lines.append("")

    if flood_coolant:
        lines.append("M9 (Coolant OFF)")
    lines.append("M5 (Spindle Stop)")
    lines.append(f"G0 Z{safe_z:.4f}")
    lines.append("M30 (End of Program)")
    lines.append("")
    return "\n".join(lines)
